### ISSUE TITLE
[Feature request] Option to copy download link

### ISSUE THREAD

**Issue by VirusBLITZ** [matthew-e-brown/download-box#2]
Would be nice to be able to right click on an item to get its download link for quick sharing and stuff :)

**Comment by matthew-e-brown** [comment]
That's a good idea. Unfotunately, there's a bit of a problem to go over first...

...what URL would you expect this to be? The `chrome.downloads` API exposes three: `url`, `finalUrl`, and `referrer`. For an example, for the Firefox installer (the link at the top-right of https://mozilla.org), those three are: 

```json
{
  "url": "https://download.mozilla.org/?product=firefox-stub&os=win&lang=en-CA",
  "finalUrl": "https://download-installer.cdn.mozilla.net/pub/firefox/releases/94.0.2/win32/en-CA/Firefox%20Installer.exe",
  "referrer": "https://www.mozilla.org/"
}
```

When you click this new button to get a shareable link, which do you expect to get? Each has their own downside. On a re-visit...

- `url` would submit a fresh request to the endpoint that **started** the download. In the Firefox example, that would send you to a GET endpoint with `product=firefox-stub`, `os=win`, and `lang=en-CA`. That would give you a *fresh* download, but it means that the link you share will not always point to the same file (i.e., if you visit that link now, it will likely not download version 94.0.2 exactly).
- `finalUrl` would point directly to the exact file you downloaded. That means you could share files directly with a link, but it has a risk of breaking if the file is generated on the fly by a server, or if it gets removed by the server maintainer.
- `referrer` points to the page from which you clicked the button. So, if you wanted to direct your friend to the webpage from which you got a file, this would be useful; "I got it from here" type of thing. This breaks, however, if the link is opened externally (e.g., you click a download link in another program like Discord and it opens in your default browser). In this case, the `referrer` property is blank. It would also break if the destination page changes their layout to remove the button you're directing your friend towards.

Presenting all three to the user would definitely be pretty rough for UX.

**Comment by VirusBLITZ** [comment]
If it were up to me then definitely the `finalUrl`, it's the reason someone would need this button, for example some websites don't give you a direct link to a file, the `finalUrl` will work at least temporarily.

Also nice is to  be able to directly paste it to a server to `wget` a file on a remote session.

It's also the expected behavior on chromes download page and on Firefox.


For the average user the normal `url` would probably work too...

**Comment by matthew-e-brown** [comment]
That's very true, I guess it is already the default for the links in the download page. Noted!

**Comment by matthew-e-brown** [comment]
I've added a button to copy the `finalUrl` (you can check it out by building manually on the `1.1-updates` branch).

The only thing I think it's missing is some kind of signal that something was copied. Maybe a popup somewhere? Maybe a tooltip before clicking? I'm not sure. Since I don't have any of that built into the app yet, I just left it as is for now.

**Comment by matthew-e-brown** [comment]
Version 1.1 is now live on the Chrome webstore with a button to copy download links. 😃

**Comment by VirusBLITZ** [comment]
Great! I'll check it out once I'm home.
