### ISSUE TITLE
Thank you =)

### ISSUE THREAD

**Issue by Sogl** [matthew-e-brown/download-box#7]
Not an issue, but...

For a long time i used the "Download - Your Download Box" extension (removed from chrome webshop long time ago) and today, after Chrome update, it stopped working. It's good that your extension appeared (looks much better). Thank you!

I'll keep you posted if I find any bugs etc.

**Comment by matthew-e-brown** [comment]
I'm very glad you are happy with the extension 😄 

*Your Download Box*'s disappearance was actually the exact reason I made this extension! I used to use it myself, and never realized it had vanished until I bought a new computer and realized the extension failed to sync. 

If you [look back at some of the older commits](https://github.com/matthew-e-brown/download-box/tree/75b0cbe76022cbb3a7ac025fc8d10753b0c6c4f9), you can actually see that I was pretty inspired by the old extension: 😛 

![Classic theme](https://user-images.githubusercontent.com/43387454/188208875-7c7e9d8d-93d8-4901-a4cf-bed625f50957.png)
